steps:

  - label: ":docker: build and upload image"
    command: ".buildkite/steps/build.sh"
    id: with-vault

  - wait

  - label: ":partyparrot: deploy to staging"
    command: "ansible-playbook -i \"$SECRET_STAGE_SERVER_IP,\" -e \"deploy_tag=$BUILDKITE_TAG\" playbooks/deploy.yaml --vault-password-file ~/vault_pass"
    id: with-vault
  
  - wait

  - block: "Release?"
    prompt: "Deploy to prod?"
    branches: master

  - wait

  - name: ":rocket: deploy to prod"
    command: "ansible-playbook -i \"$SECRET_PROD_SERVER_IP,\" -e \"deploy_tag=$BUILDKITE_TAG\" playbooks/deploy.yaml --vault-password-file ~/vault_pass"
    branches: master
    id: with-vault